{{- if .Values.rbac.create -}}
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: {{ include "sa-delete-webhook.fullname" . }}-pod-reader
  labels:
    {{- include "sa-delete-webhook.labels" . | nindent 4 }}
rules:
  - apiGroups: [""]
    resources: ["pods"]
    verbs: ["get", "list"]
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: {{ include "sa-delete-webhook.fullname" . }}-pod-reader-binding
  labels:
    {{- include "sa-delete-webhook.labels" . | nindent 4 }}
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: {{ include "sa-delete-webhook.fullname" . }}-pod-reader
subjects:
  - kind: ServiceAccount
    name: {{ include "sa-delete-webhook.serviceAccountName" . }}
    namespace: {{ .Release.Namespace }}
{{- end }}
