apiVersion: v1
kind: Service
metadata:
  name: {{ include "sa-delete-webhook.fullname" . }}
  labels:
    {{- include "sa-delete-webhook.labels" . | nindent 4 }}
spec:
  type: {{ .Values.service.type }}
  ports:
    - port: {{ .Values.service.port }}
      targetPort: tls
      protocol: TCP
      name: tls
  selector:
    {{- include "sa-delete-webhook.selectorLabels" . | nindent 4 }}
