apiVersion: admissionregistration.k8s.io/v1
kind: ValidatingWebhookConfiguration
metadata:
  name: {{ include "sa-delete-webhook.fullname" . }}
  labels:
    {{- include "sa-delete-webhook.labels" . | nindent 4 }}
  annotations:
    cert-manager.io/inject-ca-from: {{ .Values.webhook.injectCAFrom | default (printf "%s/%s-tls" .Release.Namespace (include "sa-delete-webhook.fullname" .)) }}
webhooks:
  - name: {{ include "sa-delete-webhook.fullname" . }}.{{ .Values.webhook.domain | default "omegaworld.net" }}
    clientConfig:
      service:
        name: {{ include "sa-delete-webhook.fullname" . }}
        namespace: {{ .Release.Namespace }}
        path: /validate
        port: {{ .Values.service.port | default 8443 }}
    rules:
      - apiGroups: ["*"]
        apiVersions: ["v1"]
        operations: ["DELETE"]
        resources: ["serviceaccounts"]
        scope: "Namespaced"
    admissionReviewVersions: ["v1"]
    sideEffects: None
    failurePolicy: Fail
    timeoutSeconds: 10
    namespaceSelector:
      matchExpressions:
        - key: "kubernetes.io/metadata.name"
          operator: "NotIn"
          values:
            - "kube-system"
            - "kube-public"
            - "default"
